work_dir: ./newwork_dir/ntu120/xset/TSGCNext5_bonemodern
#output_dir: ./newwork_dir/ntu120/xsub/TSGCNext_bonemodern
# feeder
feeder: feeders.feeder_ntu.Feeder
train_feeder_args:
  data_path: data/ntu120/NTU120_CSet.npz
  split: train
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: 256
  normalization: False
  random_rot: True
  p_interval: [0.5, 1]
  vel: False
  bone: True

test_feeder_args:
  data_path: data/ntu120/NTU120_CSet.npz
  split: test
  window_size: 256
  p_interval: [0.95]
  vel: False
  bone: True
  debug: False

# model
model: model.tsgcnext_5.Model
model_args:
  num_class: 120
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: 'spatial'
  drop_out: 0.4



batch_size: 32
test_batch_size: 32

nesterov: True
