work_dir: ./newwork_dir/ntu60/xsub/TSGCNext_bonemodern2x32x2

# feeder
## CUDA_VISIBLE_DEVICES=0,1 python -m torch.distributed.launch --nproc_per_node=2 main_modern.py --config config/nturgbd-cross-view/TSGCNextmodernbone.yaml --batch_size 32 --lr 4e-3 --update_freq 32 --model_ema true --model_ema_eval true --dist_url tcp://127.0.0.3:125
feeder: feeders.feeder_ntu.Feeder
train_feeder_args:
  data_path: data/ntu/NTU60_CS.npz
  split: train
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: 256
  normalization: False
  random_rot: True
  p_interval: [0.5, 1]
  vel: False
  bone: True

test_feeder_args:
  data_path: data/ntu/NTU60_CS.npz
  split: test
  window_size: 256
  p_interval: [0.95]
  vel: False
  bone: True
  debug: False

# model
model: model.tsgcnext.Model
model_args:
  num_class: 60
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: 'spatial'
  drop_out: 0.4



batch_size: 32
test_batch_size: 32

nesterov: True
