work_dir: ./newwork_dir/ntu60/xsub/TSGCNext_jointmodern
# output_dir: ./newwork_dir/ntu60/xview/TSGCNext_jointmodern
# feeder
feeder: feeders.feeder_ntu.Feeder
train_feeder_args:
  data_path: data/ntu/NTU60_CS.npz
  split: train
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: 256
  normalization: False
  random_rot: True
  p_interval: [0.5, 1]
  vel: False
  bone: False

test_feeder_args:
  data_path: data/ntu/NTU60_CS.npz
  split: test
  window_size: 256
  p_interval: [0.95]
  vel: False
  bone: False
  debug: False

# model
model: model.tsgcnext.Model
model_args:
  num_class: 60
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: 'spatial'
  drop_out: 0.4



batch_size: 32
test_batch_size: 32

nesterov: True

#finetune: newwork_dir/ntu120/xsub/TSGCNext_jointmodernstep1/checkpoint-best.pth
