work_dir: ./newwork_dir3/ntu60/xview/TSGCNext3_jointmodern
#output_dir: ./newwork_dir/ntu60/xsub/TSGCNext_jointmodern
# feeder
feeder: feeders.feeder_ntu.Feeder
train_feeder_args:
  data_path: data/newntu/NTU60_CV.npz
  split: train
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: 300
  normalization: False
  random_rot: True
  p_interval: [0.5, 1]
  vel: False
  bone: False

test_feeder_args:
  data_path: data/newntu/NTU60_CV.npz
  split: test
  window_size: 300
  p_interval: [0.95]
  vel: False
  bone: False
  debug: False

# model
model: model.net.cm_st_gcn
model_args:
  num_class: 60
  channel: 3
  window_size: 300
  num_point: 25
  num_person: 2
  mask_learning: True
  use_data_bn: True
  attention: True
  only_attention: True
  tcn_attention: False
  data_normalization: True
  skip_conn: True
  weight_matrix: 2
  only_temporal_attention: True
  bn_flag: True
  attention_3: False
  kernel_temporal: 9
  more_channels: False
  double_channel: True
  drop_connect: True
  concat_original: True
  all_layers: False
  adjacency: False
  agcn: False
  device: [0, 1]
  dv: 0.25
  dk: 0.25
  Nh: 8
  n: 4
  dim_block1: 10
  dim_block2: 30
  dim_block3: 75
  relative: False
  graph: graph.ntu_rgb_d.Graph
  visualization: False
  graph_args:
    labeling_mode: 'spatial'



batch_size: 32
test_batch_size: 32

nesterov: True
