work_dir: ./newwork_dir/k400
# output_dir: ./newwork_dir/ntu60/xview/TSGCNext_jointmodern
# feeder
feeder: feeders.feeder_ntu_2d.Feeder
train_feeder_args:
  data_path: data/HRNet/k400_pose.npz
  split: train
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: 256
  normalization: False
  random_rot: True
  p_interval: [0.5, 1]
  vel: False
  bone: False

test_feeder_args:
  data_path: data/HRNet/k400_pose.npz
  split: test
  window_size: 256
  p_interval: [0.95]
  vel: False
  bone: False
  debug: False

# model
model: model.tsgcnext_3.Model
model_args:
  num_class: 400
  num_point: 17
  num_person: 2
  graph: graph.coco.Graph
  graph_args:
    labeling_mode: 'spatial'
  drop_out: 0.4


#resume: newwork_dir/ntu60hrnet/xview/TSGCNext_jointmodern_3/checkpoint-best.pth
batch_size: 32
test_batch_size: 32

nesterov: True
